# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0002_tour_total_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_on', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('spent_time', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='activate',
            new_name='end',
        ),
        migrations.AddField(
            model_name='tour',
            name='start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourexpense',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.Tour'),
        ),
    ]
