# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-07 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0004_auto_20181203_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourexpense',
            options={'ordering': ['-id']},
        ),
    ]
